# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  ncoreapi:
    image: ncoreapi
    build:
      context: .
      dockerfile: ncoreapi/Dockerfile
    ports:
      - 5167:5167
